version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "9394:9394"
    volumes:
      - ./storage:/rails/storage
    environment:
      - RAILS_ENV=development
      - PROMETHEUS_EXPORTER_PORT=9394